# CMake generated Testfile for 
# Source directory: C:/Users/colin/Documents/far-to-go/DX12Tests
# Build directory: C:/Users/colin/Documents/far-to-go/DX12Tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DX12.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Debug/DX12Tests.exe" "--gtest_filter=DX12.Initialize")
  set_tests_properties(DX12.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DX12.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Release/DX12Tests.exe" "--gtest_filter=DX12.Initialize")
  set_tests_properties(DX12.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DX12.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/MinSizeRel/DX12Tests.exe" "--gtest_filter=DX12.Initialize")
  set_tests_properties(DX12.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DX12.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/RelWithDebInfo/DX12Tests.exe" "--gtest_filter=DX12.Initialize")
  set_tests_properties(DX12.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
else()
  add_test(DX12.Initialize.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DX12.CreateDefaultBuffer.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Debug/DX12Tests.exe" "--gtest_filter=DX12.CreateDefaultBuffer")
  set_tests_properties(DX12.CreateDefaultBuffer.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DX12.CreateDefaultBuffer.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Release/DX12Tests.exe" "--gtest_filter=DX12.CreateDefaultBuffer")
  set_tests_properties(DX12.CreateDefaultBuffer.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DX12.CreateDefaultBuffer.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/MinSizeRel/DX12Tests.exe" "--gtest_filter=DX12.CreateDefaultBuffer")
  set_tests_properties(DX12.CreateDefaultBuffer.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DX12.CreateDefaultBuffer.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/RelWithDebInfo/DX12Tests.exe" "--gtest_filter=DX12.CreateDefaultBuffer")
  set_tests_properties(DX12.CreateDefaultBuffer.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
else()
  add_test(DX12.CreateDefaultBuffer.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DX12.StorageConversion.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Debug/DX12Tests.exe" "--gtest_filter=DX12.StorageConversion")
  set_tests_properties(DX12.StorageConversion.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DX12.StorageConversion.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/Release/DX12Tests.exe" "--gtest_filter=DX12.StorageConversion")
  set_tests_properties(DX12.StorageConversion.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DX12.StorageConversion.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/MinSizeRel/DX12Tests.exe" "--gtest_filter=DX12.StorageConversion")
  set_tests_properties(DX12.StorageConversion.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DX12.StorageConversion.noArgs "C:/Users/colin/Documents/far-to-go/DX12Tests/RelWithDebInfo/DX12Tests.exe" "--gtest_filter=DX12.StorageConversion")
  set_tests_properties(DX12.StorageConversion.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;27;gtest_add_tests;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
else()
  add_test(DX12.StorageConversion.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DX12Tests "C:/Users/colin/Documents/far-to-go/DX12Tests/Debug/DX12Tests.exe")
  set_tests_properties(DX12Tests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;32;add_test;C:/Users/colin/Documents/far-to-go/DX12Tests/CMakeLists.txt;0;")
endif()
