# CMake generated Testfile for 
# Source directory: C:/Users/colin/Documents/far-to-go/GraphicsTests
# Build directory: C:/Users/colin/Documents/far-to-go/GraphicsTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Rendering.Test.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=Rendering.Test")
  set_tests_properties(Rendering.Test.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Rendering.Test.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=Rendering.Test")
  set_tests_properties(Rendering.Test.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Rendering.Test.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=Rendering.Test")
  set_tests_properties(Rendering.Test.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Rendering.Test.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=Rendering.Test")
  set_tests_properties(Rendering.Test.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(Rendering.Test.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(VirtualCamera.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Initialize")
  set_tests_properties(VirtualCamera.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(VirtualCamera.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Initialize")
  set_tests_properties(VirtualCamera.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(VirtualCamera.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Initialize")
  set_tests_properties(VirtualCamera.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(VirtualCamera.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Initialize")
  set_tests_properties(VirtualCamera.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(VirtualCamera.Initialize.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(VirtualCamera.Project.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Project")
  set_tests_properties(VirtualCamera.Project.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(VirtualCamera.Project.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Project")
  set_tests_properties(VirtualCamera.Project.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(VirtualCamera.Project.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Project")
  set_tests_properties(VirtualCamera.Project.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(VirtualCamera.Project.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=VirtualCamera.Project")
  set_tests_properties(VirtualCamera.Project.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(VirtualCamera.Project.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Mesh.Header.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=Mesh.Header")
  set_tests_properties(Mesh.Header.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Mesh.Header.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=Mesh.Header")
  set_tests_properties(Mesh.Header.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Mesh.Header.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=Mesh.Header")
  set_tests_properties(Mesh.Header.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Mesh.Header.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=Mesh.Header")
  set_tests_properties(Mesh.Header.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(Mesh.Header.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Mesh.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=Mesh.Initialize")
  set_tests_properties(Mesh.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Mesh.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=Mesh.Initialize")
  set_tests_properties(Mesh.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Mesh.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=Mesh.Initialize")
  set_tests_properties(Mesh.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Mesh.Initialize.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=Mesh.Initialize")
  set_tests_properties(Mesh.Initialize.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(Mesh.Initialize.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Mesh.Copy.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=Mesh.Copy")
  set_tests_properties(Mesh.Copy.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Mesh.Copy.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=Mesh.Copy")
  set_tests_properties(Mesh.Copy.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Mesh.Copy.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=Mesh.Copy")
  set_tests_properties(Mesh.Copy.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Mesh.Copy.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=Mesh.Copy")
  set_tests_properties(Mesh.Copy.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(Mesh.Copy.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Mesh.Move.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe" "--gtest_filter=Mesh.Move")
  set_tests_properties(Mesh.Move.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Mesh.Move.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/Release/GraphicsTests.exe" "--gtest_filter=Mesh.Move")
  set_tests_properties(Mesh.Move.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Mesh.Move.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/MinSizeRel/GraphicsTests.exe" "--gtest_filter=Mesh.Move")
  set_tests_properties(Mesh.Move.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Mesh.Move.noArgs "C:/Users/colin/Documents/far-to-go/GraphicsTests/RelWithDebInfo/GraphicsTests.exe" "--gtest_filter=Mesh.Move")
  set_tests_properties(Mesh.Move.noArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "C:/Program Files/CMake/share/cmake-3.26/Modules/GoogleTest.cmake;402;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;17;gtest_add_tests;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
else()
  add_test(Mesh.Move.noArgs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(GraphicsTests "C:/Users/colin/Documents/far-to-go/GraphicsTests/Debug/GraphicsTests.exe")
  set_tests_properties(GraphicsTests PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;22;add_test;C:/Users/colin/Documents/far-to-go/GraphicsTests/CMakeLists.txt;0;")
endif()
